Team.create!(name: "Avengers")  #Harsh
Team.create!(name: "Warriors")  #Tim
Team.create!(name: "Sonics")    #Jesus
Team.create!(name: "Lightning") #Mike

Player.create!(name: "Harsh Thakker", team_id: 1, captain: true)
Player.create!(name: "Mike Grant", team_id: 4, captain: true)
Player.create!(name: "Tim Townsend", team_id: 2, captain: true)
Player.create!(name: "Jesus Santizo", team_id: 3, captain: true , commissioner: true)
Player.create!(name: "Jason Marcus Waak", team_id: 1, commissioner: true)
Player.create!(name: "Long Nguyen", team_id: 1)
Player.create!(name: "Carlos Santizo", team_id: 2)
Player.create!(name: "Jeff Jimenez", team_id: 3)
Player.create!(name: "Matt Wurster", team_id: 2)
Player.create!(name: "Rick Jauridez", team_id: 3)
Player.create!(name: "Pete Kokosoulis", team_id: 4)
Player.create!(name: "Justin Mendheim", team_id: 3)
Player.create!(name: "Steve Kokosoulis", team_id: 2)
Player.create!(name: "John Alexander", team_id: 1)
Player.create!(name: "Manny Rodriguez", team_id: 4)
Player.create!(name: "Kenny Jerez", team_id: 3)
Player.create!(name: "Victor Santizo", team_id: 3)
Player.create!(name: "Boris Alfaro", team_id: 2)
Player.create!(name: "Rohan Thakker", team_id: 1)
Player.create!(name: "Josh Ho", team_id: 3)
Player.create!(name: "Adam Hopkins", team_id: 1)
Player.create!(name: "Rod Tiongco", team_id: 1)
Player.create!(name: "Mitchell Serranilla", team_id: 3)
Player.create!(name: "Sheedy Victor", team_id: 4)
Player.create!(name: "Georgi Georgiev", team_id: 3)
Player.create!(name: "Anthony Sorci", team_id: 3)
Player.create!(name: "Luis Salas", team_id: 4)
Player.create!(name: "Brian Cordero", team_id: 2)
Player.create!(name: "Matt Mendez", team_id: 4)
Player.create!(name: "Vergil Kelly", team_id: 2)
Player.create!(name: "Chris Orosz", team_id: 1)
Player.create!(name: "Jerry Puyot", team_id: 3)
Player.create!(name: "Desmond Fernando", team_id: 1)
Player.create!(name: "Leo Quines", team_id: 1)
Player.create!(name: "Luis Bultron", team_id: 4)
Player.create!(name: "David 'Shiggy' Lee", team_id: 2)
Player.create!(name: "Lorenz Guerrero", team_id: 4)
Player.create!(name: "Oscar Gomez", team_id: 4)
Player.create!(name: "Brandon Johnson", team_id: 2)
Player.create!(name: "Colin Nolan", team_id: 4)
Player.create!(name: "Bryan Espiritu", team_id: 2)